### ISSUE TITLE
WithMeta horaemeta link is incorrect

### ISSUE THREAD

**Issue by jimmiejams** [apache/horaedb-docs#138]
The link to horaemeta in the build tree points to the old incubator link [https://github.com/apache/incubator-horaedb-meta] instead of to the current tree (which I assume is [https://github.com/apache/horaedb/tree/main/horaemeta])

**Comment by jiacai2050** [comment]
Thanks for pointing out.

It would be great if you can submit pull requests to fix them.

**Comment by jimmiejams** [comment]
Happy to!  Will do it today.

**Comment by jiacai2050** [comment]
Any updates? @jimmiejams
