### ISSUE TITLE
Website does not document how to report issues with the website

### ISSUE THREAD

**Issue by sebbASF** [apache/horaedb-docs#150]

**Comment by jiacai2050** [comment]
Hi, could you elaborate more?

There is already a  `Create documentation issue` menu in the right side of doc.
<img width="541" alt="image" src="https://github.com/user-attachments/assets/2057bca5-1dad-43ff-8e3a-4edceb495157">

**Comment by jiacai2050** [comment]
The homepage doesn't contain the menu, it's the doc section: https://horaedb.apache.org/docs/

**Comment by jiacai2050** [comment]
> So how are people supposed to report errors in the main website?

Currently there are no obvious way, maybe we can to put a link at footer?
