### ISSUE TITLE
Add how to use remote compaction docs

### ISSUE THREAD

**Issue by jiacai2050** [apache/horaedb-docs#156]

**Comment by jiacai2050** [comment]
@LeslieKid  @Rachelint  User guide is also required, I plan to include this feature in v2.2.0

**Comment by LeslieKid** [comment]
> @LeslieKid @Rachelint User guide is also required, I plan to include this feature in v2.2.0

OK! I will work on it over the next few days.

**Comment by LeslieKid** [comment]
> @LeslieKid Any progress on this?

Yes, I have submitted #158 for this issue.

And maybe we should push the [pr#1559](https://github.com/apache/horaedb/pull/1559) in HoraeDB forward.

**Comment by jiacai2050** [comment]
> And maybe we should push the [pr#1559](https://github.com/apache/horaedb/pull/1559) in HoraeDB forward.

Yes, this is a more practical solution, but it will make the horaemeta more complex, so we will wait until some real-world user case come out.
